//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutlookAddIns.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Y:\\Merge Database\\The Merge Database_be.mdb")]
        public string Database {
            get {
                return ((string)(this["Database"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("First Name;Last Name;Job Title;Address;Phone;Mobile;Email;Website;Twitter;Instagr" +
            "am;Company on Badge")]
        public string RegistrationFields {
            get {
                return ((string)(this["RegistrationFields"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[First Name];Surname;JobTitle;;[Direct Tel No];MobileTelNumber;Email")]
        public string RegistrationDatabaseFields {
            get {
                return ((string)(this["RegistrationDatabaseFields"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Address1;Address2;Address3;Town;County;Postcode;Country;Web;Twitter;Instagram")]
        public string AddressFields {
            get {
                return ((string)(this["AddressFields"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"	{""TableName"":""TblContacts"", ""TableFields"":[
		{""FormField"":""First Name"", ""DbField"": ""[First Name]""},
        {""FormField"":""Last Name"", ""DbField"": ""Surname""},
        {""FormField"":""First Name"", ""DbField"": ""Salutation""},
        {""FormField"":""Job Title"", ""DbField"": ""JobTitle""},
        {""FormField"":""Phone"", ""DbField"": ""[Direct Tel No]""},
        {""FormField"":""Mobile"", ""DbField"": ""MobileTelNumber""},
        {""FormField"":""Email"", ""DbField"": ""Email""}
	]}")]
        public string mainJSON {
            get {
                return ((string)(this["mainJSON"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22")]
        public int CurrentVisitorExhibition {
            get {
                return ((int)(this["CurrentVisitorExhibition"]));
            }
        }
    }
}
